import { fetchReticulumAuthenticated } from "./phoenix-utils";
import defaultAvatar from "../assets/models/DefaultAvatar.glb";

// original random nicknames
// const names = [
  // "Baers-Pochard",
  // "Baikal-Teal",
  // "Barrows-Goldeneye",
  // "Blue-Billed",
  // "Blue-Duck",
  // "Blue-Winged",
  // "Brown-Teal",
  // "Bufflehead",
  // "Canvasback",
  // "Cape-Shoveler",
  // "Chestnut-Teal",
  // "Chiloe-Wigeon",
  // "Cinnamon-Teal",
  // "Comb-Duck",
  // "Common-Eider",
  // "Common-Goldeneye",
  // "Common-Merganser",
  // "Common-Pochard",
  // "Common-Scoter",
  // "Common-Shelduck",
  // "Cotton-Pygmy",
  // "Crested-Duck",
  // "Crested-Shelduck",
  // "Eatons-Pintail",
  // "Falcated",
  // "Ferruginous",
  // "Freckled-Duck",
  // "Gadwall",
  // "Garganey",
  // "Greater-Scaup",
  // "Green-Pygmy",
  // "Grey-Teal",
  // "Hardhead",
  // "Harlequin",
  // "Hartlaubs",
  // "Hooded-Merganser",
  // "Kelp-Goose",
  // "King-Eider",
  // "Lake-Duck",
  // "Laysan-Duck",
  // "Lesser-Scaup",
  // "Long-Tailed",
  // "Maccoa-Duck",
  // "Mallard",
  // "Mandarin",
  // "Marbled-Teal",
  // "Mellers-Duck",
  // "Merganser",
  // "Northern-Pintail",
  // "Orinoco-Goose",
  // "Paradise-Shelduck",
  // "Plumed-Whistler",
  // "Puna-Teal",
  // "Pygmy-Goose",
  // "Radjah-Shelduck",
  // "Red-Billed",
  // "Red-Crested",
  // "Red-Shoveler",
  // "Ring-Necked",
  // "Ringed-Teal",
  // "Rosy-Billed",
  // "Ruddy-Shelduck",
  // "Salvadoris-Teal",
  // "Scaly-Sided",
  // "Shelduck",
  // "Shoveler",
  // "Silver-Teal",
  // "Smew",
  // "Spectacled-Eider",
  // "Spot-Billed",
  // "Spotted-Whistler",
  // "Steamerduck",
  // "Stellers-Eider",
  // "Sunda-Teal",
  // "Surf-Scoter",
  // "Tufted-Duck",
  // "Velvet-Scoter",
  // "Wandering-Whistler",
  // "Whistling-duck",
  // "White-Backed",
  // "White-Cheeked",
  // "White-Winged",
  // "Wigeon",
  // "Wood-Duck",
  // "Yellow-Billed"
// ];


// korean nickname. edit 2023.06.29
const names = [
  "곰 오리",
  "청록색 바이칼",
  "황금눈 손수레",
  "파란 지폐",
  "파란 오리",
  "푸른 날개",
  "갈색 청록색",
  "곱슬머리",
  "캔버스백",
  "고요한 동굴",
  "청록색 밤나무",
  "콜라가방",
  "시나몬 바다",
  "빛나는 오리",
  "보통의 오렌지",
  "모두의 골든아이",
  "평범한 비오리",
  "아보카도 샌드위치",
  "우리의 만두",
  "우리 비오리",
  "작은 털뭉치",
  "볏 오리",
  "언덕 호랑이",
  "연못 고방오리",
  "콘크리트 그릇",
  "철분 마라탕",
  "주근깨 오리",
  "콜라 자동차",
  "아보카도 스머프",
  "치즈 분화구",
  "가을인가봐요",
  "회색과 청록색",
  "바위같은 주먹",
  "버들나무 여왕",
  "초전도체",
  "두건을 쓴 비오리",
  "켈프 거위",
  "오성산왕",
  "호수 오리",
  "육지 고래상어",
  "카카오 베어",
  "긴꼬리 달팽이",
  "마코아 아코마",
  "청둥오리",
  "만다린 오렌지",
  "청록색 대리석",
  "메롱메롱 오리",
  "비오리 시오리",
  "북방 호랑이",
  "망고 거위",
  "천국 껍질오리",
  "휘파람 깃털",
  "발빠짐 주의",
  "조그마한 거위",
  "초록 신용카드",
  "빨간 청구서",
  "붉은 볏",
  "빨간 삽",
  "둥근 목걸이",
  "청록색 고리",
  "장밋빛 청구서",
  "대단한 참새",
  "청록색 매미",
  "비늘 코뿔소",
  "아궁이 고양이",
  "단단한 찹쌀떡",
  "카카오 비빔면",
  "향기로운 비행기",
  "안경 자동차",
  "백금 마을",
  "점박이 나라",
  "표범 공항",
  "따듯한 솜털",
  "청록색 순록",
  "파도 기린",
  "술취한 오리",
  "벨벳 들판",
  "방황하는 휘파람",
  "아보카도 김밥",
  "앞으로 앞으로",
  "백발 부엉이",
  "하얀 날개",
  "시작할까요",
  "나무오리",
  "노란 마음"
];

function chooseRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateRandomName() {
  return `${chooseRandom(names)}-${Math.floor(10000 + Math.random() * 10000)}`;
}

export async function fetchRandomDefaultAvatarId() {
  const defaultAvatarEndpoint = "/api/v1/media/search?filter=default&source=avatar_listings";
  const defaultAvatars = (await fetchReticulumAuthenticated(defaultAvatarEndpoint)).entries || [];
  if (defaultAvatars.length === 0) {
    // If reticulum doesn't return any default avatars, just default to the duck model. This should only happen
    // when running against a fresh reticulum server, e.g. a local ret instance.
    return new URL(defaultAvatar, location.href).href;
  }
  const avatarIds = defaultAvatars.map(avatar => avatar.id);
  return chooseRandom(avatarIds);
}
